apiVersion: hitachivantara.com/v1
kind: solutionpackage
metadata:
  name: "data-transformation-editor-0.9.51"
spec:
  chartName: "data-transformation-editor"
  chartVersion: "0.9.51"
  # optional:
  appVersion: "0.9.51"
  # optional:
  images:
    - "hiromuhota/webspoon:0.9.51"