# Downloads and installs Kubespray 2.14 of Kubernetes 1.18
# Run from: /etc/ansible/playbooks
- name: Install Kubespray
  hosts: "{{ groups['installer'][0] }}"
  become: false
  gather_facts: true
  vars:
    installer_home: /installers
    release: release-2.14
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
    - name: Ping Nodes
      ping:
      tags: ['info']

    - name: Update all packages
      yum:
       name: '*'
      tags: [install]  
  
    # Downloads kubespray into the mounted playbooks folder
    # This is therefore, persisted on your local filesystem
    - name: Get Kubespray if required
      get_url:
        url: 'https://github.com/kubernetes-sigs/kubespray/archive/refs/heads/{{release}}.zip'
        dest: "{{ installer_home }}/kubespray-{{release}}.zip"
      when: kubespray.stat.exists == false
      tags: [install]
 
    # Extracts kubespray into the mounted playbooks folder
    # This is therefore, persisted on your local filesystem
    - name: Unarchive Kubespray-{{ release }}
      unarchive:
        src: "{{ installer_home }}/kubespray-{{release}}.zip"
        dest: "{{ installer_home }}"
      when: kubespray.stat.exists == false
      tags: [install]

    - name: Update pip dependancies
      pip:
        requirements: requirements.txt
        chdir: "{{ installer_home }}/kubespray-{{release}}"
      tags: [cluster]
  
    - name: Re-Check if Kubespray has extracted
      stat:
        path: "{{ installer_home }}/kubespray-{{release}}"
      register: kubespray
      #when: kubespray.stat.exists == false
      tags: [install]

    # May need to update path  
    - name: Copy extra-vars.yml
      copy:
        src: "extra-vars.yml"
        dest: "{{ installer_home }}/kubespray-{{release}}/extra-vars.yml"
      tags: [install]

    # May need to update path 
    - name: Copy hosts-skytap.yml
      copy:
        src: "hosts-skytap.yml"
        dest: "{{ installer_home }}/kubespray-{{release}}/hosts-skytap.yml"
      tags: [install]

    - debug: 
        msg: "Kubspray Exists: {{ kubespray }}-{{release}}"
      tags: [install]
      
    # Run the kubespray playbook on the hosts
    # - include: "{{ kube_path }}/kubespray-{{release}}/cluster.yml"

    - debug:
        msg:
          - "kubespray is available in {{ installer_home }}/kubespray-{{release}}"
          - "cd {{ installer_home }}/kubespray-{{release}}"
          - "ansible-playbook -b -v -i hosts-skytap.yml --extra-vars='@extra-vars.yml' cluster.yml"
      when: kubespray.stat.exists == true
      tags: [info, install]
    
    - debug:
        msg:
          - "kubespray download and unpack failed!"
      when: kubespray.stat.exists == false
      tags: [info, install]