# Installation of Dataflow Designer 0.7.0
- name: Install Dataflow Designer 0.7.0
  become: false
  gather_facts: true
  hosts: "{{ groups['installer'][0] }}"
  vars:
    logs_dir: /installers/logs
    env_file: /installers/Dataflow-Designer-0.7.0/installer-ldd/env.properties
    designer_home: /installers/Dataflow-Designer-0.7.0
    designer_archive: dataflow-designer-0.7.0.tgz
    installer_archive: installer-ldd.zip
    foundry_home: /installers/Foundry-Control-Plane-2.2.1/Foundry
        
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:

    # Check for Dataflow Designer directory
    - name: Check if the 'Dataflow Designer' directory exists
      stat:
        path: "{{ designer_home }}"
      register: designer
      tags: 
        - info

    - debug: 
        msg: "Dataflow Designer directory exists: {{ designer.stat.exists }}"
      tags: 
        - info

    # Creates Dataflow Designer install directory - if required
    - name: Creates 'Dataflow Designer' directory
      file:
        path: "{{ designer_home }}"
        state: directory
      when: designer.stat.exists == false
      tags: 
        - info

    # Unarchive Dataflow Designer 0.7.0
    - name: Unarchive {{ designer_archive }}
      unarchive:
        src: "{{ designer_home }}/{{ designer_archive }}"
        dest: "{{ designer_home }}"
        creates: "{{ designer_home }}/dataflow-designer-0.7.0"
      tags: 
        - unpack  

    # Unarchive Dataflow Designer Installer-0.7.0.zip
    - name: Unarchive {{ installer_archive }}
      unarchive:
        src: "{{ designer_home }}/{{ installer_archive }}"
        dest: "{{ designer_home }}"
        creates: "{{ designer_home }}/installer-ldd"
      tags: 
        - unpack

    # Prepare env.properties
    - name: get secret for solution-control-plane-sso-client
      shell: 'kubectl get secrets keycloak-client-secret-solution-control-plane-sso-client -n hitachi-solutions --template=\{\{.data.CLIENT_SECRET\}\} | base64 --decode'
      register: scp_sso_client_secret
      tags: 
        - env

    # Get the 'foundry' password 
    - name: get foundry password
      shell: "kubectl get keycloakusers -n hitachi-solutions keycloak-user -o jsonpath='{.spec.user.credentials[0].value}'"
      register: foundry
      tags: 
        - env
    
    # Backup env.properties
    - name: Backup env.properties
      shell: | 
        cp {{ env_properties_file }} {{ logs_dir }}/{{ env_properties_file | basename }}.{{ 10000 | random }}.bak  
    
    # Replace the variables in env.properties
    - name: Replace key=value pairs in env.properties file, add new values after the hostname line
      lineinfile:
        path: "{{ env_properties_file }}"
        regexp: '^[# ]*{{ item.search }}\s*=\s*'
        line: '{{ item.replace }}'
        insertafter: '^[# ]*hostname\s*=\s*'
        backup: yes
      with_items:
        - { search: 'hostname', replace: 'hostname={{ apiserver_loadbalancer_domain_name }}' }
        - { search: 'registry', replace: 'registry={{ master_node_for_registry }}:{{ master_node_for_registry_port }}' }
        - { search: 'username', replace: 'username=foundry' }
        - { search: 'foundry_client_secret', replace: 'foundry_client_secret={{ foundry_client_secret }}' }
        - { search: 'password', replace: 'password={{ foundry_user_password.stout }}' }
        - { search: 'volume_host', replace: 'volume_host={{ nfs_host }}' }
        - { search: 'volume_path', replace: 'volume_path={{ nfs_path }}' }

    # Upload Dataflow Designer 0.7.0 solutions to Registry.
    - name: Upload dataflow designer-0.7.0 to Registry
      shell: 
        chdir: "{{ foundry_home }}"
        cmd: ./bin/upload-solutions.sh -C {{ designer_home }}/dataflow-designer-0.7.0/charts/ -I {{ designer_home }}/dataflow-designer-0.7.0/images/ 
             -k ~/.kube/config -n hitachi-solutions -D true 2>&1 | tee -a {{ logs_dir }}/upload-designer-0.7.0.log
      async: 2500
      poll: 30
      register: ret
      failed_when: "ret.rc > 0 or 'no such file' in ret.stdout"
      tags: 
        - upload_designer  

    # Install Dataflow Designer 0.7.0
    - name: Install Dataflow Designer 0.7.0
      shell: 
        chdir: "{{ designer_home }}/installer-ldd"
        cmd: "./install.sh 2>&1 | tee -a {{ logs_dir }}/install-designer-0.7.0.log"
      async: 1000
      poll: 30
      register: ret
      failed_when: "ret.rc > 0 or 'no such file' in ret.stdout"
      tags: 
        - designer

    # Check for Running and Complete Pods
    - name: Confirm Install
      shell: "kubectl get pods -n hitachi-solutions | grep -i -e '[RC][uo][nm][np][il][ne]' | wc -l"
      register: designer_pods
      tags: 
       - designer

    #Check for Non-Running or Failing Pods
    - name: Confirm application status (URL or pods?)
      shell: "kubectl get pods -n hitachi-solutions | grep -iv -e '[RC][uo][nm][np][il][ne]'"
      register: results
      tags: 
        - designer

