## Install Foundry Control Plane
- name: Install Foundry Services
  hosts: "{{ groups['installer'][0] }}"
  become: false
  # become_method: sudo
  gather_facts: true
  remote_user: installer
  vars:
    base_foundry_dir: /installers/Foundry
    foundry_root: /installers/Foundry-Control-Plane-2.2.1.tgz
    foundry_home: /installers/Foundry/Foundry-Control-Plane-2.2.1
    istio_root: /installers/Foundry/Foundry-Control-Plane-2.2.1/istio/Foundry-Istio-2.2.0.49.tgz
    istio_home: /installers/Foundry/Foundry-Control-Plane-2.2.1/Foundry-Istio-2.2.0.49
    metrics_root: /installers/metrics-addon-1.0.0.tgz
    metrics_home: /installers/Foundry/metrics-addon-1.0.0
    upload_root: /installers/Foundry-Solution-Upload-2.2.1.tgz
    upload_home: /installers/Foundry/Foundry-Solution-Upload-2.2.1
    log_dir: /installers/logs

    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
    - name: Ping Nodes
      ping:
      tags: ['info']

    - name: Update all packages
      yum:
       name: '*'
      tags: [info, install] 

    # Checks for the logs directory
    - name: Check for 'logs' directory
      stat:
        path: "{{ logs_dir }}"
      register: logs
      tags: [info] 

    - debug: 
        msg: "logs Exists: {{ logs.stat.exists }}"
      tags: [info]           

    # Create a log directory - if required
    - name: Create Log Directory
      file:
       path: "{{ log_dir }}"
       state: directory
      when: logs.stat.exists == false
      tags: [info, install]

    # Check for Foundry directory
    - name: Check if the Foundry directory exists
      stat:
        path: "{{ foundry_home }}"
      register: foundry
      tags: [info]

    - debug: 
        msg: "foundry directory exists: {{ foundry.stat.exists }}"
      tags: [info]

    # Creates Foundry install directory -if required
    - name: Create Foundry directory
      file:
        path: "{{ foundry_home }}"
        state: directory
      when: foundry.stat.exists == false
      tags: [info, install]
    
    # Unpacks Foundry Solution Control Plane 
    - name: Unpack Foundry
      unarchive: 
        src: "{{ foundry_root }}"
        dest: "{{ foundry_home }}"
      tags: [unpack] 
    
    # Checks for the Istio directory
    - name: Check for 'Istio' directory
      stat:
        path: "{{ istio_home }}"
      register: istio
      tags: [info] 

    - debug: 
        msg: "istio directory exists: {{ istio.stat.exists }}"
      tags: [info]     

    # Creates Istio install directory -if required
    - name: Create Istio directory
      file:
        path: "{{ istio_home }}"
        state: directory
      when: istio.stat.exists == false
      tags: [info, install]     

    # Unpacks Istio 
    - name: Unpack Istio
      unarchive: 
        src: "{{ istio_root }}"
        dest: "{{ istio_home }}"
      tags: [unpack]  

    # Foundry requires istio and cert-manager be installed
    - name: Install Cluster Services
      shell: 
        chdir: "{{ foundry_home }}"
        cmd: ./bin/install-cluster-services.sh -I -r {{ master_node_for_registry }}:{{ master_node_for_registry_port }} -D true 2>&1 | tee -a {{ log_dir }}/install-cluster-services.log
      async: 2500
      poll: 30
      register: ret
      failed_when: "ret.rc > 0 or 'no such file' in ret.stdout"
      tags: [install_cs]

    # Install Hitachi CRDs
    - name: Run Custom Resource Definitions Script
      shell: 
        chdir: "{{ foundry_home }}"
        cmd: ./bin/apply-crds.sh -e -r {{ master_node_for_registry }}:{{ master_node_for_registry_port }} --insecure -D true 2>&1 | tee -a {{ log_dir }}/apply-crds.log
      async: 2500
      poll: 30
      register: ret
      failed_when: "ret.rc > 0 or 'no such file' in ret.stdout"
      tags: [install, install_cs]

    # Install the Soluton Control Plane services
    - name: Install Foundry Control Plane
      shell: 
        chdir: "{{ foundry_home }}"
        cmd: ./bin/install-control-plane.sh -I -r {{ master_node_for_registry }}:{{ master_node_for_registry_port }} -D true -c https://{{ apiserver_loadbalancer_domain_name }} 2>&1 | tee -a {{ log_dir }}/install-control-plane.log
      async: 2500
      poll: 30
      register: ret
      failed_when: "ret.rc > 0 or 'no such file' in ret.stdout"
      tags: [install, install_cp]

    # Check for Metrics directory
    - name: Check if Metrics directory exists
      stat:
        path: "{{ metrics_home }}"
      register: metrics
      tags: [unpack]

    - name: Metrics Directory located
      debug:
        msg: "Directory {{ metrics_home }} present"
      when: metrics.stat.isdir is defined and metrics.stat.isdir

    # Unpacks Metrics addon 
    - name: Unpack Metrics
      unarchive: 
        src: "{{ metrics_root }}"
        dest: "{{ base_foundry_dir }}"
      tags: [unpack] 

    - name: Install Metrics Addon
      shell: 
        chdir: "{{ foundry_home }}"
        cmd: ./bin/apply-crds.sh -r {{ master_node_for_registry }}:{{ master_node_for_registry_port }} -C {{ metrics_home }}/crd-charts/ -k ~/.kube/config --insecure -x -D true 2>&1 | tee -a {{ log_dir }}/install-metrics-add-on.log
      async: 2500
      poll: 30
      register: ret
      failed_when: "ret.rc > 0 or 'no such file' in ret.stdout"
      tags: [install, metrics]

    - name: Upload Metrics Add-On Solution
      shell: 
        chdir: "{{ foundry_home }}"
        cmd: ./bin/upload-solutions.sh -C {{metrics_home }}/charts/ -I {{metrics_home }}/images/ -k ~/.kube/config -n hitachi-solutions -D true 2>&1 | tee -a {{ log_dir }}/install-metrics-add-on.log
      async: 2500
      poll: 30
      register: ret
      failed_when: "ret.rc > 0 or 'no such file' in ret.stdout"
      tags: [install, metrics]

    - name: Confirm Foundry
      shell: "{{ item }}"
      with_items:
        - "kubectl get all -n hitachi-solutions"
      register: foundry_pods
      tags: ['never', 'install_cp', 'info']

    - name: Confirm Foundry User
      shell: "kubectl get keycloakusers -n hitachi-solutions keycloak-user -o jsonpath='{.spec.user.credentials[0].value}'"
      register: foundry_pass
      tags: ['never', 'install_cp', 'info']

    - name: Foundry URLs
      debug:
        msg: 
        - " Installation complete.... "
        - "          Logs can be found in {{ log_dir }}"
        - "          URL: https://{{ apiserver_loadbalancer_domain_name }}/hitachi-solutions/hscp-hitachi-solutions/solution-control-plane/"
        - "          as foundry/{{ foundry_pass.stdout }}"
      tags: ['never', 'install_cp', 'info']